name: wb20201105

on:
  schedule:
    - cron: '*/25 22 * * * '
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./wb/requirements.txt 
        
      - name: 'run wb20201105' 
        run: python3 ./wb/wb.py 
        env:
            WEIBO_SIGN_COOKIE: ${{ secrets.WEIBO_SIGN_COOKIE }}
            DJJ_BARK_COOKIE: ${{ secrets.DJJ_BARK_COOKIE }}
            DJJ_SEVER_JIANG: ${{ secrets.DJJ_SEVER_JIANG }}


